security:
    encoders:
        Schuma\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_AUTOR:    ROLE_USER
        ROLE_ADMIN:    ROLE_AUTHOR
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     /
            remember_me:
                key:        %secret%


    access_control:
            #- { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            #- { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            #- { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
