<?php

namespace Schuma\FaqBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
    public function getLast($number = 5){
        $qb = $this->createQueryBuilder('q');
        $qb->setMaxResults($number)
            ->orderBy('q.date', 'DESC');

        return $qb->getQuery()
            ->getResult();
    }
}
