schuma_blog_main:
    path: /
    defaults: {_controller: SchumaBlogBundle:Blog:main}

_article:
    resource: "@SchumaBlogBundle/Resources/config/routing_article.yml"
    prefix:   /articles

_event:
    resource: "@SchumaBlogBundle/Resources/config/routing_event.yml"
    prefix:   /evenements

_comment:
    resource: "@SchumaBlogBundle/Resources/config/routing_comment.yml"
    prefix:   /commentaires

schuma_blog_master:
    path: /master
    defaults: {_controller: SchumaBlogBundle:Blog:master}

schuma_blog_association:
    path: /association
    defaults: {_controller: SchumaBlogBundle:Blog:association}

schuma_blog_promo:
    path: /promo
    defaults: {_controller: SchumaBlogBundle:Blog:promo}
