# src/Schuma/BlogBundle/Resources/config/routing.yml

schuma_blog_main:
    path: /
    defaults: {_controller: SchumaBlogBundle:Blog:main}


schuma_blog_master:
    path: /master
    defaults: {_controller: SchumaBlogBundle:Blog:master}


schuma_blog_association:
    path: /association
    defaults: {_controller: SchumaBlogBundle:Blog:association}


schuma_blog_evenement:
    path: /evenements
    defaults: {_controller: SchumaBlogBundle:Blog:evenements}


schuma_blog_promo:
    path: /promo
    defaults: {_controller: SchumaBlogBundle:Blog:promo}
    


schuma_blog_articles:
    path: /articles
    defaults: {_controller: SchumaBlogBundle:Article:articles}


schuma_blog_voirArticle:
    path: /article/{id}
    defaults: {_controller: SchumaBlogBundle:Article:voirArticle}
    requirements:
        id: \d+

    
schuma_blog_ajouter:
    path: /ajouter
    defaults: {_controller: SchumaBlogBundle:Article:addArticle}


schuma_blog_editArticle:
    path: /edit_article/{id}
    defaults: {_controller: SchumaBlogBundle:Article:editArticle}
    requirements:
        id: \d+
