_question:
    resource: "@SchumaFaqBundle/Resources/config/routing_question.yml"
    prefix:   /questions

_category:
    resource: "@SchumaFaqBundle/Resources/config/routing_category.yml"
    prefix:   /categories

_answer:
    resource: "@SchumaFaqBundle/Resources/config/routing_answer.yml"
    prefix:   /reponses
