<?php

namespace Schuma\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    function getListByArticle($articleId){
        return $this->createQueryBuilder('c')
            ->where('c.article = :articleId')
            ->setParameter('articleId', $articleId)
            ->orderBy('c.date', 'DESC')
            ->getQuery()
            ->getResult()
            ;
    }

    function getCommentNumber($articleId) {
        return $this->createQueryBuilder('c')
            ->select('COUNT(c.id)')
            ->where('c.article = :articleId')
            ->setParameter('articleId', $articleId)
            ->getQuery()
            ->getSingleScalarResult()
            ;
    }

    public function getLast($number = 5){
        $qb = $this->createQueryBuilder('c');
        $qb->setMaxResults($number)
            ->orderBy('c.date', 'DESC');
        return $qb->getQuery()
            ->getResult();
    }
}
