parameters:
    schuma_user.security_service.class: Schuma\UserBundle\Services\SecurityService

services:
    schuma_user.security_service:
        class: %schuma_user.security_service.class%
        calls:
            - [ setContainer,[ @service_container ] ]
#        arguments: [@service_id, "plain_value", %parameter%]
